import { faDotCircle, faSquare, faCircle as farCircle, faStar as farStar } from '@fortawesome/free-regular-svg-icons'

import {
    faArrowsAltV,
    faBars,
    faCaretDown,
    faCheck,
    faCheckCircle,
    faCheckSquare,
    faChevronDown,
    faChevronLeft,
    faChevronRight,
    faChevronUp,
    faCircle,
    faEdit,
    faExclamation,
    faExclamationTriangle,
    faInfoCircle,
    faMinus,
    faMinusSquare,
    faPaperclip,
    faPlus,
    faSortDown,
    faSortUp,
    faStar,
    faStarHalf,
    faStepBackward,
    faStepForward,
    faSync,
    faTimes,
    faTimesCircle,
} from '@fortawesome/free-solid-svg-icons'
import type { IconAliases } from 'vuetify'

const aliases: IconAliases = {
    collapse: faChevronUp,
    complete: faCheck,
    cancel: faTimesCircle,
    close: faTimes,
    delete: faTimesCircle,
    clear: faTimesCircle,
    success: faCheckCircle,
    info: faInfoCircle,
    warning: faExclamation,
    error: faExclamationTriangle,
    prev: faChevronLeft,
    next: faChevronRight,
    checkboxOn: faCheckSquare,
    checkboxOff: faSquare,
    checkboxIndeterminate: faMinusSquare,
    delimiter: faCircle,
    sortAsc: faSortUp,
    sortDesc: faSortDown,
    expand: faChevronDown,
    menu: faBars,
    subgroup: faCaretDown,
    dropdown: faCaretDown,
    radioOn: faDotCircle,
    radioOff: farCircle,
    edit: faEdit,
    ratingEmpty: farStar,
    ratingFull: faStar,
    ratingHalf: faStarHalf,
    loading: faSync,
    first: faStepBackward,
    last: faStepForward,
    unfold: faArrowsAltV,
    file: faPaperclip,
    plus: faPlus,
    minus: faMinus,
}

export default aliases
